<?php
namespace Ov\Component\Salaov\Administrator\Controller;
\defined('_JEXEC') or die;
use Joomla\CMS\MVC\Controller\BaseController; use Joomla\CMS\Factory; use Joomla\CMS\Session\Session;
class AvailabilityController extends BaseController {
 public function save(){ Session::checkToken() or die('Invalid token'); $app=Factory::getApplication(); $db=Factory::getContainer()->get('DatabaseDriver'); $date=$app->input->getString('visit_date'); $cap=max(0,$app->input->getInt('capacity',20)); $avail=$app->input->getInt('available',1); $note=$app->input->getString('note'); if($date){ $this->upsertDay($db,$date,$avail,$cap,$note); } $this->setRedirect('index.php?option=com_salaov&view=availability','Disponibilita salvata'); }
 public function saveRange(){ Session::checkToken() or die('Invalid token'); $app=Factory::getApplication(); $db=Factory::getContainer()->get('DatabaseDriver'); $from=$app->input->getString('date_from'); $to=$app->input->getString('date_to'); $weekdays=$app->input->get('weekdays',[],'array'); $weekdays=array_map('intval',$weekdays); $cap=max(0,$app->input->getInt('capacity',20)); $avail=$app->input->getInt('available',1); $note=$app->input->getString('note'); $slotsText=$app->input->getRaw('slots_text'); $replaceSlots=$app->input->getInt('replace_slots',1); $staffIds=array_map('intval',$app->input->get('staff_ids',[],'array')); $replaceStaff=$app->input->getInt('replace_staff',1); $count=0; if($from && $to && $weekdays){ $start=new \DateTimeImmutable($from); $end=new \DateTimeImmutable($to); if($end<$start){ [$start,$end]=[$end,$start]; } for($d=$start;$d<=$end;$d=$d->modify('+1 day')){ if(!in_array((int)$d->format('N'),$weekdays,true)){ continue; } $date=$d->format('Y-m-d'); $this->upsertDay($db,$date,$avail,$cap,$note); if($replaceSlots){ $this->saveDaySlots($db,$date,$slotsText,$cap); } if($replaceStaff){ $this->saveDayStaff($db,$date,$staffIds); } $count++; } } $this->setRedirect('index.php?option=com_salaov&view=availability',$count.' giorni aggiornati'); }
 public function saveDay(){ Session::checkToken() or die('Invalid token'); $app=Factory::getApplication(); $db=Factory::getContainer()->get('DatabaseDriver'); $date=$app->input->getString('single_date'); $cap=max(0,$app->input->getInt('single_capacity',20)); $avail=$app->input->getInt('single_available',1); $note=$app->input->getString('single_note'); $slotsText=$app->input->getRaw('single_slots_text'); $staffIds=array_map('intval',$app->input->get('single_staff_ids',[],'array')); if($date){ $this->upsertDay($db,$date,$avail,$cap,$note); $this->saveDaySlots($db,$date,$slotsText,$cap); $this->saveDayStaff($db,$date,$staffIds); } $this->setRedirect('index.php?option=com_salaov&view=availability','Giorno personalizzato salvato'); }
 public function delete(){ $id=Factory::getApplication()->input->getInt('id'); if($id){ $db=Factory::getContainer()->get('DatabaseDriver'); $db->setQuery('SELECT visit_date FROM #__salaov_day_capacity WHERE id='.(int)$id); $date=$db->loadResult(); $db->setQuery('DELETE FROM #__salaov_day_capacity WHERE id='.(int)$id)->execute(); if($date){ $db->setQuery('DELETE FROM #__salaov_day_slots WHERE visit_date='.$db->quote($date))->execute(); $db->setQuery('DELETE FROM #__salaov_day_staff WHERE visit_date='.$db->quote($date))->execute(); } } $this->setRedirect('index.php?option=com_salaov&view=availability','Regola eliminata'); }
 private function upsertDay($db,string $date,int $avail,int $cap,string $note):void{ $q=$db->getQuery(true)->insert('#__salaov_day_capacity')->columns(['visit_date','available','capacity','note'])->values($db->quote($date).','.(int)$avail.','.(int)$cap.','.$db->quote($note)); $q.=' ON DUPLICATE KEY UPDATE available=VALUES(available), capacity=VALUES(capacity), note=VALUES(note)'; $db->setQuery($q)->execute(); }
 private function saveDaySlots($db,string $date,string $text,int $defaultCap):void{ $db->setQuery('DELETE FROM #__salaov_day_slots WHERE visit_date='.$db->quote($date))->execute(); $lines=preg_split('/\r\n|\r|\n/',trim($text)); $ord=1; foreach($lines as $line){ $line=trim($line); if($line===''){ continue; } $parts=array_map('trim',explode('|',$line)); $title=$parts[0]??('Fascia '.$ord); $start=$parts[1]??''; $end=$parts[2]??''; $cap=(int)($parts[3]??$defaultCap); if(!preg_match('/^\d{2}:\d{2}$/',$start) || !preg_match('/^\d{2}:\d{2}$/',$end)){ continue; } $obj=(object)['visit_date'=>$date,'title'=>$title,'start_time'=>$start.':00','end_time'=>$end.':00','capacity'=>max(0,$cap),'published'=>1,'ordering'=>$ord++]; $db->insertObject('#__salaov_day_slots',$obj); } }
 private function saveDayStaff($db,string $date,array $staffIds):void{ $db->setQuery('DELETE FROM #__salaov_day_staff WHERE visit_date='.$db->quote($date))->execute(); foreach(array_unique(array_filter($staffIds)) as $sid){ $obj=(object)['visit_date'=>$date,'staff_id'=>(int)$sid]; $db->insertObject('#__salaov_day_staff',$obj); } }
}
